name: Deploy tutorial.html to GitHub Pages

on:
  push:
    branches:
      - main  

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7 

      - name: Install AsciiDoctor
        run: gem install asciidoctor

      - name: Clean previous builds
        run: rm -rf build/*

      - name: Build the tutorial and other artifacts 
        run: make 
      
      - name: List build directory contents
        run: ls -al ./build

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build/tutorial.html 


  deploy:
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

